image: gradle:jdk17-alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
    gradle --build-cache build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

check:
  stage: test
  script:
   gradle check

test:
  stage: test
  script:
   gradle test

run_server:
  stage: test
  script:
    - mkdir -p run # Ensure the run directory exists
    - cd run
    - echo "eula=true" > eula.txt
    - cd ..
    - gradle runServer -PrunDir=run &
    - sleep 60 # Adjust this based on how long it typically takes for your server to start
    - >
      while ! grep -q "Done (" run/server.log; do
        if grep -q "Exception" run/server.log; then
          echo "Server crashed!"
          exit 1
        fi
        sleep 5
      done
      
after_script:
  - echo "End CI"