cimage: gradle:jdk17-alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
    gradle --build-cache build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

check:
  stage: test
  script:
   gradle check

test:
  stage: test
  script:
   gradle test


after_script:
  - echo "End CI"