cimage: gradle:jdk17-alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
    gradle --build-cache build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

check:
  stage: test
  script:
   - gradle check

test:
  stage: test
  script:
   - gradle test

server:
  stage: test
  script:
    - mkdir -p run # Ensure the run directory exists
    - cd run
    - echo "eula=true" > eula.txt
    - cd ..
    - ./gradlew runServer -PrunDir=run &
    - sleep 10 # Adjust this based on how long it typically takes for your server to start
    - tail -f run/server.log | grep -q "Done (" # Adjust this based on the actual log message


after_script:
  - echo "End CI"